---
title: "Atmospheric Circulation"
author: "Michael Hunt"
date: "March 30, 2016"
output: html_document
---

## Problem 1: Hadley Cell

### 1a

The angular momentum $M$ of a parcel on the surface of the Earth at latitude \phi may be expressed,

$$M=a\cos\phi(u+\Omega a\cos\phi)$$


Here $a$ is the radius of the Earth, \Omega is the angular velocity of the Earth's rotation, and $u$ is the velocity of the parcel in the zonal direction.

The angular momentum of a parcel at rest (i.e. when u=0) increases as one moves toward the equator. If the circulation of the atmosphere is zonally symmetric, angular momentum is conserved. Under these conditions the maximum angular momentum achievable by any parcel is that of a stationary parcel at rest at the equator. The maximum velocity of such a parcel at any given latitude is the velocity it achieves if it conserves its angular momentum starting from rest at the equator. Write an expression for this maximum velocity, which we will denote $u_M$, as a function of the latitude $\phi$.

Answer:

The angular momentum for a parcel at rest at the equator is given by,

$$M=a^2\Omega$$

Since we are assuming the parcel conserves its angular momentum, its value of angular momentum must always be equal to this initial value. Thus, we have,

$$a^2\Omega=a\cos\phi\left(u_M+\Omega a \cos\phi\right)$$

Rearranging gives

$$
\begin{align*}
u_M&=a\Omega\left(\frac{1}{\cos \phi}-\cos \phi\right)\\
&=a\Omega\sin\phi\tan\phi
\end{align*}
$$

### 1b
We now consider the radiative-convective equilibrium solution described in the lecture videos. In this solution, the atmospheric winds are in thermal wind balance with the temperature gradient. But is there enough angular momentum on the Earth to sustain such winds?

Suppose the radiative-convective equilibrium solution for the atmospheric temperature is isothermal in the vertical (not realistic!), and has a latitudinal dependence of the form,

$$\ln\left(\frac{T}{T_0}\right) = 1 - \frac{1}{3}\Delta_H\left(3\sin^2(\phi) - 1\right)$$

where $T$ is the temperature, with global mean $T_0$, and $\Delta H$ is the radiative-convective equilibrium temperature difference between equator and pole.

The thermal wind equation may be written

$$2\Omega\sin\phi\frac{\partial u}{\partial z} = -\frac{g}{a}\frac{\partial \ln(T)}{\partial \phi}.$$

Using the expression for $\ln(T)$, find an expression for the zonal velocity at the tropopause, where $z=H$, that is in thermal wind balance with the radiative-convective equilibrium solution for the temperature. We denote this velocity $u_T$. You may assume that the winds at the surface are negligible.


